name: Bash Script Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x server_util.sh
          chmod +x tests/run_tests.sh

      - name: Run tests
        run: ./tests/run_tests.sh
