name: Unit Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x src/server_util.sh
          chmod +x tests/unit_tests.sh

      - name: Run tests
        run: ./tests/unit_tests.sh
